#!/bin/bash
# plsw-to-module.sh -- Post-process PL/SW .s output into a linkable module
#
# Usage: ./scripts/plsw-to-module.sh <module.s> <prefix> <imports_file> <output.s> <output.meta>
#
# imports_file: one line per imported symbol (e.g., "util_SLEN")
# The script:
#   1. Prefixes all labels with <prefix>_
#   2. Adds jump table slots for imports
#   3. Replaces calls to imported symbols with jump table calls
#   4. Generates .meta file with EXPORT/IMPORT
#
# For the main module (has _start), keeps _start unprefixed.

set -euo pipefail

INPUT="$1"
PREFIX="$2"
IMPORTS_FILE="$3"
OUTPUT="$4"
META="$5"

# Read imports into array
IMPORTS=()
IMPORT_ORIGINAL=()
if [ -f "$IMPORTS_FILE" ] && [ -s "$IMPORTS_FILE" ]; then
    while IFS= read -r line; do
        [ -z "$line" ] && continue
        [[ "$line" == \;* ]] && continue
        IMPORTS+=("$line")
    done < "$IMPORTS_FILE"
fi
NUM_IMPORTS=${#IMPORTS[@]}

# Build awk script for label prefixing + jump table insertion
awk -v pfx="$PREFIX" -v num_imports="$NUM_IMPORTS" \
    -v imports_str="$(IFS=,; echo "${IMPORTS[*]}")" '
BEGIN {
    split(imports_str, imports, ",")
    # Build import lookup: original_label -> slot
    for (i = 1; i <= num_imports; i++) {
        imp_label[imports[i]] = i - 1
        # Also track the _LABEL form (PL/SW emits _PROCNAME)
        imp_label["_" imports[i]] = i - 1
    }
    emitted_jtbl = 0
    in_runtime = 0
    past_runtime = 0
    in_data = 0
    is_main = (pfx == "main")
}

# Skip PL/SW runtime preamble for library modules
!is_main && /^[[:space:]]*\.text/ && !past_runtime { in_runtime = 1; next }
!is_main && /^_start:/ { in_runtime = 1; next }
!is_main && /^_halt:/ { in_runtime = 1; next }
!is_main && /^_UART_PUTCHAR:/ { in_runtime = 1; next }
!is_main && /^_UART_PUTS:/ { in_runtime = 1; next }
in_runtime && /^[[:space:]]+jmp[[:space:]]+\(r1\)/ {
    in_runtime = 0; past_runtime = 1
    # Emit jump table here
    if (num_imports > 0 && !emitted_jtbl) {
        print "        .text"
        print "; --- jump table (" num_imports " slots) ---"
        for (i = 1; i <= num_imports; i++) {
            printf "%s_jtbl_%d:\n", pfx, i-1
            print "        .byte   0xC7, 0x00, 0x00, 0x00"
        }
        print ""
        emitted_jtbl = 1
    }
    next
}
in_runtime { next }

# For main module, emit jump table after _start preamble
is_main && /^_halt:/ && !emitted_jtbl {
    print $0  # keep _halt
    if (num_imports > 0) {
        print ""
        print "; --- jump table (" num_imports " slots) ---"
        for (i = 1; i <= num_imports; i++) {
            printf "%s_jtbl_%d:\n", pfx, i-1
            print "        .byte   0xC7, 0x00, 0x00, 0x00"
        }
        print ""
    }
    emitted_jtbl = 1
    next
}

# Skip duplicate _MAIN in library modules
!is_main && /^[[:space:]]*\.globl[[:space:]]+_MAIN/ { next }
!is_main && /^_MAIN:/ { in_dummy_main = 1; next }
in_dummy_main && /^[[:space:]]+jmp[[:space:]]+\(r1\)/ { in_dummy_main = 0; next }
in_dummy_main { next }

# Prefix labels and references
{
    line = $0

    # Skip .data directive (keep it as-is)
    if (line ~ /^[[:space:]]*\.data/) { print line; in_data = 1; next }

    # Prefix label definitions: _PROCNAME: -> _prefix_PROCNAME:
    # But keep _start, _halt, _UART_* for main module
    if (match(line, /^_([A-Za-z][A-Za-z0-9_]*):/, arr)) {
        lbl = arr[1]
        if (is_main && (lbl == "start" || lbl == "halt" || lbl ~ /^UART/ || lbl ~ /^uart/)) {
            # Keep unprefixed
        } else {
            gsub("^_" lbl ":", "_" pfx "_" lbl ":", line)
        }
    }

    # Prefix internal labels: L123: -> prefix_L123:
    while (match(line, /L([0-9]+):/, arr)) {
        old = "L" arr[1] ":"
        new = pfx "_L" arr[1] ":"
        gsub(old, new, line)
    }

    # Prefix label references in instructions (la, call, bra, etc.)
    # _PROCNAME -> _prefix_PROCNAME (but not _start, _UART_*)
    while (match(line, /,_([A-Za-z][A-Za-z0-9_]*)/, arr) || match(line, / _([A-Za-z][A-Za-z0-9_]*)/, arr)) {
        lbl = arr[1]
        if (lbl == "start" || lbl == "halt" || lbl ~ /^UART/ || lbl ~ /^uart/) break
        # Check if this is an imported symbol -- redirect to jump table
        jt_lbl = pfx "_" lbl
        if (("_" lbl) in imp_label) {
            slot = imp_label["_" lbl]
            repl = pfx "_jtbl_" slot
            gsub("_" lbl, repl, line)
        } else {
            gsub("_" lbl, "_" pfx "_" lbl, line)
        }
        break  # one replacement at a time to avoid infinite loop
    }

    # Prefix L-label references
    while (match(line, /[, ]L([0-9]+)([^0-9:]|$)/, arr)) {
        old = "L" arr[1]
        new = pfx "_L" arr[1]
        sub(old, new, line)
    }

    print line
}
' "$INPUT" > "$OUTPUT"

# Generate .meta file
{
    echo "; ${PREFIX}.meta -- generated by plsw-to-module.sh"
    echo "MODULE $PREFIX"
    echo ""

    # Exports: find all prefixed .globl labels (procedures)
    grep "\.globl.*_${PREFIX}_" "$OUTPUT" 2>/dev/null | while read -r _ label; do
        echo "EXPORT $label 0x0000"  # offset filled by listing
    done

    # Jump table
    if [ "$NUM_IMPORTS" -gt 0 ]; then
        if [ "$PREFIX" = "main" ]; then
            echo ""
            echo "JTBL 0x0008"  # after _start(4) + _halt(4)
        else
            echo ""
            echo "JTBL 0"
        fi
        for i in "${!IMPORTS[@]}"; do
            echo "IMPORT $i ${IMPORTS[$i]}"
        done
    fi
} > "$META"

echo "  Module $PREFIX: $(wc -l < "$OUTPUT") lines, $NUM_IMPORTS imports" >&2
