number = 2
slug = "m4-builtins"
status = "completed"
description = "Add SNOBOL4 predicate builtins: IDENT(A,B), DIFFER(A,B), GT(A,B), EQ(A,B), LE..."
role = "production"
context_files = []
created_at = "2026-04-06T20:10:57"
completed_at = "2026-04-07T09:27:46"
